# Generated by Django 3.2.2 on 2021-05-20 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hall_number', models.CharField(max_length=2)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('conditions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='media/admin_lte/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40)),
                ('description', models.TextField()),
                ('trailer_url', models.URLField()),
                ('release_date', models.DateField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seance_format', models.CharField(choices=[('3D', '3D'), ('2D', '2D'), ('IMAX', 'IMAX')], max_length=4, verbose_name='Формат фильма')),
                ('price', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance_hall', to='cinema_site.hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seance_movie', to='cinema_site.movie')),
            ],
        ),
        migrations.CreateModel(
            name='SeoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('keywords', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('seo_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('seat_place', models.IntegerField()),
                ('is_booked', models.BooleanField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_buyer', to=settings.AUTH_USER_MODEL)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_seance', to='cinema_site.seance')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('phone1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('phone2', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('is_basic', models.BooleanField(default=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_banner', to='cinema_site.image')),
                ('seo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_seo', to='cinema_site.seodata')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_poster', to='cinema_site.seodata'),
        ),
        migrations.AddField(
            model_name='movie',
            name='seo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_seo', to='cinema_site.seodata'),
        ),
        migrations.AddField(
            model_name='hall',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_banner', to='cinema_site.image'),
        ),
        migrations.AddField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_cinema', to='cinema_site.cinema'),
        ),
        migrations.AddField(
            model_name='hall',
            name='layout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_layout', to='cinema_site.image'),
        ),
        migrations.AddField(
            model_name='hall',
            name='seo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_seo', to='cinema_site.seodata'),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('coordinates', models.CharField(max_length=120)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_logo', to='cinema_site.image')),
            ],
        ),
        migrations.AddField(
            model_name='cinema',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_banner', to='cinema_site.image'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='logo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_logo', to='cinema_site.image'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='seo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_site.seodata'),
        ),
    ]
