# Generated by Django 3.2.2 on 2021-05-20 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinema_site', '0002_auto_20210520_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_banner', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='mode',
            field=models.CharField(choices=[('NEWS', 'Новость'), ('EVENT', 'Акция')], max_length=5, null=True, verbose_name='Тип статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_seo', to='cinema_site.seodata'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_banner', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_logo', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cinema_seo', to='cinema_site.seodata'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_logo', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_banner', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_cinema', to='cinema_site.cinema'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_layout', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hall_seo', to='cinema_site.seodata'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_poster', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie_seo', to='cinema_site.seodata'),
        ),
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_banner', to='cinema_site.image'),
        ),
        migrations.AlterField(
            model_name='page',
            name='seo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_seo', to='cinema_site.seodata'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='hall',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seance_hall', to='cinema_site.hall'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seance_movie', to='cinema_site.movie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='seance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_seance', to='cinema_site.seance'),
        ),
    ]
