# Generated by Django 3.2.2 on 2021-05-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0004_auto_20210521_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_2d',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='is_3d',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='is_imax',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
