# Generated by Django 3.2.2 on 2021-05-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0006_auto_20210521_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='gallery',
        ),
    ]
