# Generated by Django 3.2.2 on 2021-05-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0007_remove_movie_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieGallery',
        ),
    ]
