# Generated by Django 3.2.2 on 2021-05-22 08:49

import cinema_site.services.media_services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0008_delete_moviegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('images'))),
                ('movie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_site.movie')),
            ],
        ),
    ]
