# Generated by Django 3.2.2 on 2021-05-24 09:34

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0013_auto_20210524_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.FilePathField(default='image', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('<django.db.models.fields.FilePathField>')),
        ),
    ]
