# Generated by Django 3.2.2 on 2021-05-24 09:36

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0014_auto_20210524_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('<django.db.models.fields.CharField>')),
        ),
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.CharField(max_length=30),
        ),
    ]
