# Generated by Django 3.2.2 on 2021-05-24 09:48

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0015_auto_20210524_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('images')),
        ),
    ]
