# Generated by Django 3.2.2 on 2021-05-24 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0016_auto_20210524_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hall',
            name='slug',
        ),
    ]
