# Generated by Django 3.2.2 on 2021-05-24 09:57

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0017_remove_hall_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='banner',
            field=models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('halls/banners')),
        ),
        migrations.AlterField(
            model_name='hall',
            name='layout',
            field=models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('halls/layouts')),
        ),
    ]
