# Generated by Django 3.2.2 on 2021-05-24 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0018_auto_20210524_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 5, 24, 11, 3, 19, 585982)),
            preserve_default=False,
        ),
    ]
