# Generated by Django 3.2.2 on 2021-05-24 11:22

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0019_hall_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default=213, upload_to=cinema_site.services.media_services.UploadToPathAndRename('movies/posters')),
            preserve_default=False,
        ),
    ]
