# Generated by Django 3.2.2 on 2021-05-24 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0021_auto_20210524_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviegalleryimage',
            name='movie',
        ),
        migrations.DeleteModel(
            name='CinemaGalleryImage',
        ),
        migrations.DeleteModel(
            name='MovieGalleryImage',
        ),
    ]
