# Generated by Django 3.2.2 on 2021-05-24 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0022_auto_20210524_1241'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('hall_number', 'cinema')},
        ),
    ]
