# Generated by Django 3.2.2 on 2021-05-25 11:30

import cinema_site.services.media_services
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0023_alter_hall_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('is_active', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('news/banners'))),
                ('seo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_seo', to='cinema_site.seodata')),
            ],
        ),
    ]
