# Generated by Django 3.2.2 on 2021-05-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0027_auto_20210525_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(db_index=True),
        ),
    ]
