# Generated by Django 3.2.2 on 2021-05-25 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0028_alter_news_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='created',
            new_name='publication',
        ),
    ]
