# Generated by Django 3.2.2 on 2021-05-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0030_auto_20210525_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='sdgdg',
        ),
        migrations.AddField(
            model_name='news',
            name='publication',
            field=models.DateField(db_index=True, default='2020-09-15'),
            preserve_default=False,
        ),
    ]
