# Generated by Django 3.2.2 on 2021-05-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0032_news_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='video_url',
            new_name='trailer_url',
        ),
    ]
