# Generated by Django 3.2.2 on 2021-05-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0034_rename_news_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='mode',
            field=models.CharField(choices=[('NEWS', 'Новость'), ('EVENT', 'Акция')], default='NEWS', max_length=5, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
