# Generated by Django 3.2.2 on 2021-05-26 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0035_article_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='mode',
            field=models.CharField(choices=[('NEWS', 'Новость'), ('EVENTS', 'Акция')], max_length=6, verbose_name='Тип'),
        ),
    ]
