# Generated by Django 3.2.2 on 2021-05-27 03:07

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0037_auto_20210527_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='banner',
            field=models.ImageField(default=1, upload_to=cinema_site.services.media_services.UploadToPathAndRename('pages/banners')),
            preserve_default=False,
        ),
    ]
