# Generated by Django 3.2.2 on 2021-05-27 03:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0038_alter_page_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='phone1',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='page',
            name='phone2',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
