# Generated by Django 3.2.2 on 2021-05-27 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0039_auto_20210527_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema_site.gallery'),
        ),
    ]
