# Generated by Django 3.2.2 on 2021-05-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0042_auto_20210527_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
