# Generated by Django 3.2.2 on 2021-06-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0045_auto_20210529_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
