# Generated by Django 3.2.2 on 2021-06-06 13:09

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0046_auto_20210605_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='banner',
            field=models.ImageField(default=1, upload_to=cinema_site.services.media_services.UploadToPathAndRename('contacts/banner')),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('row', 'seat_place', 'seance')},
        ),
    ]
