# Generated by Django 3.2.2 on 2021-06-06 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0047_auto_20210606_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='banner',
        ),
    ]
