# Generated by Django 3.2.2 on 2021-06-11 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0049_contacts_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(max_length=100)),
                ('reverse', models.URLField(max_length=300)),
                ('user_ip', models.GenericIPAddressField()),
                ('time_execution', models.DecimalField(decimal_places=7, max_digits=10)),
                ('utm', models.CharField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
