# Generated by Django 3.2.2 on 2021-06-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0050_logger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logger',
            old_name='reverse',
            new_name='referer',
        ),
    ]
