# Generated by Django 3.2.2 on 2021-06-11 10:41

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0052_alter_logger_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='file',
            field=models.FileField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('html_templates')),
        ),
    ]
