# Generated by Django 3.2.2 on 2021-06-13 07:13

import cinema_site.services.media_services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0054_alter_emailtemplate_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('bg_format', models.CharField(choices=[('photo_bg', 'Фон-фото'), ('simple_bg', 'Простой фон')], default='photo_bg', max_length=10, verbose_name='Формат фона')),
                ('image', models.ImageField(upload_to=cinema_site.services.media_services.UploadToPathAndRename('background'))),
            ],
        ),
    ]
