# Generated by Django 3.2.2 on 2021-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_site', '0055_backgroundimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='backgroundimage',
            name='top_banners_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
